'use client';
import Link from 'next/link';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { useCart } from '@/hooks/useCart';
import { Minus, Plus, X, ArrowLeft, ShoppingBag } from 'lucide-react';

export default function CartPage() {
  const { items, updateQuantity, removeItem, totalPrice } = useCart();
  const formatPrice = (cents: number) => `$${(cents / 100).toFixed(2)}`;
  return <div className="min-h-screen bg-white"><Navigation/><div className="px-6 pb-20 pt-24 lg:pt-32"><div className="mx-auto max-w-4xl"><Link href="/shop" className="mb-8 inline-flex items-center gap-2 text-sm text-black/50 transition-colors hover:text-black"><ArrowLeft className="h-4 w-4" />Continue Shopping</Link><h1 className="mb-10 font-serif text-4xl font-light sm:text-5xl">Shopping Cart</h1>{items.length===0? <div className="py-20 text-center"><ShoppingBag className="mx-auto mb-4 h-12 w-12 text-black/10"/><p className="mb-4 text-lg text-black/40">Your cart is empty</p><Link href="/shop" className="border-b border-black pb-1 text-sm uppercase tracking-widest transition-opacity hover:opacity-60">Browse Products</Link></div> : <div className="flex flex-col gap-12 lg:flex-row"><div className="flex-1"><div className="space-y-6">{items.map((item)=><div key={item.productId} className="flex gap-4 border-b border-black/5 pb-6"><div className="h-32 w-24 shrink-0 bg-[#f6f6f6]"><img src={item.image} alt={item.name} className="h-full w-full object-cover" /></div><div className="flex flex-1 flex-col justify-between"><div><h3 className="text-sm font-medium">{item.name}</h3><p className="mt-1 text-sm text-black/50">{formatPrice(item.price)}</p></div><div className="flex items-center justify-between"><div className="flex items-center gap-3 border border-black/10"><button onClick={()=>updateQuantity(item.productId,item.quantity-1)} className="p-2 transition-colors hover:bg-black/5"><Minus className="h-3 w-3"/></button><span className="w-6 text-center text-sm">{item.quantity}</span><button onClick={()=>updateQuantity(item.productId,item.quantity+1)} className="p-2 transition-colors hover:bg-black/5"><Plus className="h-3 w-3"/></button></div><button onClick={()=>removeItem(item.productId)} className="p-2 text-black/30 transition-colors hover:text-black"><X className="h-4 w-4"/></button></div></div></div>)}</div></div><div className="w-full lg:w-80"><div className="bg-[#f6f6f6] p-6 lg:p-8"><h2 className="mb-6 text-xs font-medium uppercase tracking-widest">Order Summary</h2><div className="mb-6 space-y-3"><div className="flex justify-between text-sm"><span className="text-black/50">Subtotal</span><span>{formatPrice(totalPrice)}</span></div><div className="flex justify-between text-sm"><span className="text-black/50">Shipping</span><span>Calculated at checkout</span></div></div><div className="mb-6 border-t border-black/10 pt-4"><div className="flex justify-between"><span className="font-medium">Total</span><span className="font-medium">{formatPrice(totalPrice)}</span></div></div><Link href="/checkout" className="block w-full bg-black py-4 text-center text-sm font-medium uppercase tracking-widest text-white transition-colors hover:bg-black/80">Proceed to Checkout</Link></div></div></div>}</div></div><Footer/></div>;
}
